print("Rules: Press enter after every statement (excluding riddle where u have to answer it)", '\n', "Here are code digits for the alphabets to answer your riddle :", '\n' ,"a=0, b=1, c=2, d=3, e=4, f=5, g=6, h=7, i=8, j=9, k=!, l=@, m=#, n=$, o=%, p=^, q=&, r=*, s=(, t=), u=[, v=], w={, x=:, y=/ and z=_")
start=input("Welcome to my Riddle Zone!!   ")
intro=input("Let me tell u the rules. I will ask you a riddle, and u have to answer it. If you answer it correct, you will get to know about a secret thing, or else, your game will end at that spot only.   ")
execute=input("Let's Begin!!   ")
riddle=input("I am in this world with a value of something, which can be nothing after my end, because I can or cannot be in the category of my group, which is to overcome it by being special. Who am I?? :")
if riddle in ['0 @8]8$6 148$6', '@8]8$6 148$6']:
    print("Well Done!! Here is your reward... You are Noob.")
elif riddle in['Batman vs Riddler', 'Batman vs Joker', 'Batman vs riddler', 'Batman vs joker', 'Batman vs GitHub']:
    print("In the first version during the Golden Age, Batman's first appearance in Detective Comics #27, he is already operating as a crime fighter. Batman's origin is first presented in Detective Comics #33 (Nov. 1939), and is later fleshed out in Batman #47. As these comics state, Bruce Wayne is born to Dr. Thomas Wayne and his wife Martha, two very wealthy and charitable Gotham City socialites in 1915. Bruce is brought up in Wayne Manor, with it's wealthy splendor, and lives a happy and privileged existence until the age of eight, when his parents are killed by a small-timed criminal named Joe Chill while on their way home from a movie theater. Bruce Wayne swears an oath to rid the city of the evil that had taken his parents' lives. He engages in intense intellectual and physical training; however, he realizes that these skills alone would not be enough. Criminals are superstitious and cowardly lot, Wayne remarks, so my disguise must be able to strike terror into their hearts. I must be a creature of the night, black, terrible... As if responding to his desires, a bat suddenly flies through the window, inspiring Bruce to take on the persona of Batman.", '\n', '\n', "In early strips, Batman's career as a vigilante earns him the ire of the police. During this period, Wayne has a fiancee named Julie Madison. Wayne takes in an orphaned circus acrobat, Dick Grayson, who becomes his sidekick, Robin. Batman also becomes a founding member of the Justice Society of America, although he, like Superman, is an honorary member, and thus only participates occasionally. Batman relationship with the law thaws quickly, and he is made an honorary member of Gotham City police department. During this time, butler Alfred Pennyworth arrives at Wayne Manor, and after deducing the Dynamic Duo secret identities joins their service.")
else:
    print("Opps!! This is a wrong answer..")
